name: CI for Pygame

# ▼▼▼ Вот это обязательно! ▼▼▼
on:
  push:
    branches: [ "main" ]  # Запуск при пуше в main
  pull_request:
    branches: [ "main" ]  # Запуск при PR в main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run linter (flake8)
        run: flake8 . --count --show-source --statistics
      - name: Run tests
        run: pytest
