name: CI for Pygame

on:  # ▼▼▼ Это обязательно! ▼▼▼
  push:
    branches: [ "master" ]  # Срабатывает при пуше в main
  pull_request:
    branches: [ "master" ]  # Срабатывает при PR в main
# ▲▲▲ Критическая часть ▲▲▲

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
